### PR TITLE
The common cycles interface proposal

### PR DESCRIPTION
**Pull request by quintolet**
This is a proposal to establish a standard interface on `cycles_transfer`.

Please help review and express your opinions. Thanks!

[Rendered page can be access here](https://github.com/quintolet/cycles-common/blob/main/proposal/cycles_transfer.md)

### CODE REVIEW

**Comment by chenyan-dfinity** [comment]
There is a `IC.deposit_cycles` method that does exactly this, see https://sdk.dfinity.org/docs/interface-spec/index.html#ic-deposit_cycles

In Motoko, you can write the following code to transfer cycles freely.
```
let IC = actor "aaaaa-aa" : actor { deposit_cycles: shared { canister_id : canister_id } -> async (); };
Cycles.add(1_000_000_000);
await IC.deposit_cycles({ canister_id = destination_canister_id });
```

**Comment by quintolet** [comment]
> There is a `IC.deposit_cycles` method that does exactly this, see https://sdk.dfinity.org/docs/interface-spec/index.html#ic-deposit_cycles
> 
> In Motoko, you can write the following code to transfer cycles freely.
> 
> ```
> let IC = actor "aaaaa-aa" : actor { deposit_cycles: shared { canister_id : canister_id } -> async (); };
> Cycles.add(1_000_000_000);
> await IC.deposit_cycles({ canister_id = destination_canister_id });
> ```

Good to know! Thanks for the pointer! Do you know if it circumvents the restriction that ordinary application subnet cannot send cycles to a verified one?

However, it still seems the destination canister would have no idea who sent the cycles and how much was deposited.  This proposal here solves that problem. I should revise the proposal to clarify this point.

**Comment by chenyan-dfinity** [comment]
Right, it doesn't know who sends it, just that you don't need a special accept method to accept the cycles.

> ordinary application subnet cannot send cycles to a verified one

That probably needs an NNS proposal.

Also curious how this proposal gets implemented? It seems you will need some system level support from the IC?

**Comment by quintolet** [comment]
> Also curious how this proposal gets implemented? It seems you will need some system level support from the IC?

At the moment I don't think so. As the example code already shows this interface can work in a variety of use cases.

But it is a big ask for developers to follow a standard or convention that is not enforced at system level. We'll see how it goes.

**Comment by honopu** [comment]
> 
> 
> There is a `IC.deposit_cycles` method that does exactly this, see https://sdk.dfinity.org/docs/interface-spec/index.html#ic-deposit_cycles
> 
> In Motoko, you can write the following code to transfer cycles freely.
> 
> ```
> let IC = actor "aaaaa-aa" : actor { deposit_cycles: shared { canister_id : canister_id } -> async (); };
> Cycles.add(1_000_000_000);
> await IC.deposit_cycles({ canister_id = destination_canister_id });
> ```

what's the type 'canister_id', Text?

**Comment by chenyan-dfinity** [comment]
It should be `Principal` type.

**Comment by honopu** [comment]
In ` Cycles.add(1_000_000_000)  `,  ` 1_000_000_000 ` is  the cylces transferred?

**Comment by chenyan-dfinity** [comment]
Yes, you can see a similar example here: https://github.com/dfinity/examples/blob/master/motoko/actor_reference/src/actor_reference/main.mo

**Comment by honopu** [comment]
Thanks for your answers!

**Pull request closed without merging**
